<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>JazeOS weekly digest — week of {{ $weekStartsOn }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 720px; margin: 24px auto; color: #1f2937; line-height: 1.5; padding: 0 16px; }
        h1 { font-size: 20px; margin-bottom: 0; }
        h2 { font-size: 16px; margin-top: 32px; }
        .meta { color: #6b7280; font-size: 12px; margin-top: 4px; }
        pre { background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; border-radius: 6px; white-space: pre-wrap; word-wrap: break-word; font-family: ui-monospace, SFMono-Regular, monospace; font-size: 13px; line-height: 1.5; }
        footer { color: #9ca3af; font-size: 11px; margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    </style>
</head>
<body>
    <h1>JazeOS weekly digest</h1>
    <div class="meta">Week of {{ $weekStartsOn }}</div>

    @if ($bodyHtml)
        {!! $bodyHtml !!}
    @else
        <pre>{{ $body }}</pre>
    @endif

    <footer>
        Generated by the weekly-digest agent. Disable in your tenant settings, or by clearing the
        <code>AGENT_WEEKLY_DIGEST_ENABLED</code> environment variable.
    </footer>
</body>
</html>
